behaviors:
  mecanumAgentDiscreteICMGailLarge:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 4096
      learning_rate: 3.0e-4
      beta: 1e-3
      learning_rate_schedule: linear
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8

    # Configuration of the neural network
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 512
      num_layers: 1
      memory:
       use_recurrent: true
       sequence_length: 128
       memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 5.0e8
    time_horizon: 512
    summary_freq: 2000
    keep_checkpoints: 20
    checkpoint_interval: 50000
    threaded: true
    reward_signals:
      # Environment rewards
      extrinsic:
        strength: 1.0
        gamma: 0.99
      # Curiosity module
      curiosity:
        strength: 0.0125
        gamma: 0.99
        network_settings:
          hidden_units: 256
      # GAIL
      gail:
        gamma: 0.99
        encoding_size: 128
        demo_path: C:\Users\zacho\Documents\Repos\Unity\Autonomous Vehicle Agents\Assets\Demonstrations\mecanumdiscrete.demo
        strength: 0.01
        use_vail : false

  mecanumAgentDiscreteICMGailSmall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 1e-3
      learning_rate_schedule: linear
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8

    # Configuration of the neural network
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 256
      num_layers: 1
      memory:
       use_recurrent: true
       sequence_length: 64
       memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 5.0e8
    time_horizon: 256
    summary_freq: 2000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    reward_signals:
      # Environment rewards
      extrinsic:
        strength: 1.0
        gamma: 0.99
      # Curiosity module
      curiosity:
        strength: 0.01
        gamma: 0.99
        network_settings:
          hidden_units: 256
      # GAIL
      gail:
        gamma: 0.99
        encoding_size: 128
        demo_path: C:\Users\zacho\Documents\Repos\Unity\Autonomous Vehicle Agents\Assets\Demonstrations\mecanumdiscrete.demo
        strength: 0.008

  mecanumAgentDiscreteRNDGailSmall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 1e-3
      learning_rate_schedule: linear
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 8

    # Configuration of the neural network
    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 256
      num_layers: 1
      memory:
       use_recurrent: true
       sequence_length: 64
       memory_size: 256

    # Trainer configurations common to all trainers
    max_steps: 5.0e8
    time_horizon: 256
    summary_freq: 2000
    keep_checkpoints: 5
    checkpoint_interval: 50000
    threaded: true
    reward_signals:
      # Environment rewards
      extrinsic:
        strength: 1.0
        gamma: 0.99
      # Random Network Distillation module
      rnd:
        gamma: 0.99
        strength: 0.01
        network_settings:
          hidden_units: 64
          num_layers: 3
        learning_rate: 0.0001
      # GAIL
      gail:
        gamma: 0.99
        encoding_size: 128
        demo_path: C:\Users\zacho\Documents\Repos\Unity\Autonomous Vehicle Agents\Assets\Demonstrations\mecanumdiscrete.demo
        strength: 0.008
